### ISSUE TITLE
Implement "OnionShare-Core" shared codebase for Android and iOS

### ISSUE THREAD

**Issue by n8fr8** [onionshare/onionshare-shared#1]
Is it possible? A good idea?

Go or Rust?

What does it need to do?

**Comment by n8fr8** [comment]
(just to clarify, this is all non-user interface code)

- start/stop an http web server running on localhost at a random or specified port
- manage links to files / packages / zips for sharing
- generate download urls for sharing that point to packages on localhost web server
- track / report on progress of downloads via listener interface/callbacks

**Comment by grote** [comment]
Thanks for kicking this off Nathan!

The title says that the shared codebase is only meant for Android and iOS, so the existing python code should stay pure python and not use that same code as well?

What would be the scope of the shared codebase? Only webserver related things or also Tor?

Besides Go and Rust, another option would be [Kotlin multi-platform](https://kotlinlang.org/lp/mobile/).

While I really like the idea of sharing as much code as possible between as much platforms as possible, I am a bit worried that here specifically introducing big dependencies between projects might put the project schedule at risk. Going with Kotlin at least on one platform could have the benefit of migrating another platform later to that same Kotlin backend code, especially if developed with that goal in mind.

**Comment by micahflee** [comment]
I think it makes sense for this shared codebase to basically re-implement [`onionshare_cli.web`](https://github.com/onionshare/onionshare/tree/develop/cli/onionshare_cli/web).

This covers starting and stopping http services, implementing all of the paths for the given mode (share, receive, website, or chat), and also communicating to the GUI, so e.g. when someone is downloading or uploading the UI can display a progress bar.

It doesn't cover any UI, or any communications with tor.

I think to begin with this should just be for Android and iOS, with the goal of desktop eventually using it as well. Since the scope of the mobile apps will likely be smaller (like maybe _just_ share mode to begin with), then only some of the functionality from `onionshare_cli.web` needs to be implemented.

Since I'd like to eventually share code between Android, iOS, and desktop, I think my vote is Go or Rust. I'm slightly more familiar with Rust, but I wouldn't be opposed to Go at all. I don't have a strong preference.

## The Web class

Here's how the `Web` class is currently implemented in OnionShare desktop. This shared library doesn't necessarily have to work exactly like this.

- An instance of the `Web` class represents the web server for an OnionShare service, e.g. an open tab of a specific mode
- A [`ModeSettings`](https://github.com/onionshare/onionshare/blob/develop/cli/onionshare_cli/mode_settings.py) object (which can get loaded and saved to disk in JSON, if the tab is persisted) is passed into `Web` when initializing it so it knows what it needs to do.

Let me describe that next...

## ModeSettings

Here's what a typical _share mode_ `ModeSettings` looks like:

```json
{
  "onion": {
    "private_key": "UAStylP/ZggwimI7NzOd3FCAtMDXhcXoyYke09flZ3PF0pjEK0Ij3EsZWJtpzM0jYoZ5hdchp+HZc/M+uzUiww==",
    "client_auth_priv_key": "IUOM33PXTSY5RCYRAUKN3F2MHIOU33HCPN3QJ7FDYWJ7H52JLCMA",
    "client_auth_pub_key": "ZAOV6CXS6JNQA2VFYRUG5Q2HGTVQLEIUM4ETCNNFHCIOO3XQHUQA"
  },
  "persistent": {
    "mode": "share",
    "enabled": true
  },
  "general": {
    "title": null,
    "public": false,
    "autostart_timer": false,
    "autostop_timer": false,
    "service_id": "dpwsslxichoi265xcw4y2hokmmlbkn4ebn2h76sxzkilyobxqxzakxqd"
  },
  "share": {
    "autostop_sharing": true,
    "filenames": [
      "/home/user/Documents/isos/debian-11.0.0-amd64-netinst.iso",
      "/home/user/code/dotfiles",
      "/home/user/Pictures/Screenshot from 2021-08-20 13-21-43.png",
      "/home/user/Pictures/Screenshot from 2021-08-27 15-15-00.png"
    ]
  },
  "receive": {
    "data_dir": "/home/user/OnionShare",
    "webhook_url": null,
    "disable_text": false,
    "disable_files": false
  },
  "website": {
    "disable_csp": false,
    "filenames": []
  },
  "chat": {
    "room": "default"
  }
}
```

- `onion` we can ignore (this also gets passed into the `Onion` singleton, which creates an ephemeral onion service)
- `persistent` we can see that the mode is `share` and that persistence is enabled
- `general` has common settings across all modes
  - `title` (optional) a custom title for the OnionShare service, that gets displayed in the HTML that's served
  - `public` a bool that describes if the service is public or not. Public services don't have any authentication, private services have http basic auth with a random password ([soon](https://github.com/onionshare/onionshare/pull/1404), this will be switched to v3 client auth). Also, if `public` is false, for basic auth there's password guessing limitations, where the server automatically stops with too many invalid guesses
  - `autostart_timer` (optional) the service is set to automatically start at this timestamp
  - `autostop_timer` (optional) the service is set to automatically start at this timestamp
  - `service_id` this is the onion service ID (the domain without ".onion"), which gets set after starting the service the first time, to help build the URL
- `share` has share-specific settings
  - `autostop_sharing` the checkbox in the GUI for this setting says, "Stop sharing after files have been sent (uncheck to allow downloading individual files)" -- this is a security feature to ensure that files stay online for the shortest time possible. The `Web` object makes a compressed version of all the files available, and after it's been downloaded it immediately stops the web service. The web services shows a directory listing of all files and folders shared, and if this is disabled you can download individual files instead of the whole compressed set of files.
  - `filenames` is a list of files and folders to share
- Since the mode is `share`, we can ignore `receive`, `website`, and `chat`

## Back to the Web class

All OnionShare web services have these routes:

- `/static_[random-16char-hex]/` this is the folder for [static css, img, and js resources](https://github.com/onionshare/onionshare/tree/develop/cli/onionshare_cli/resources/static) (it has random characters in its name to avoid route collisions, in case someone is sharing a folder called "static")
- error handles for 401, 403, 404, 405, and 500

Here are the routes share mode uses:

- `/` this is the root directory listing of all the files being shared
- `/download` this downloads a compressed version of the all the files being shared, called `onionshare_[randomchars].zip` if multiple files are being shared -- if just one file is being shared, it downloads the file directly using http gzip compression. After the file is done downloading, if `autostop_sharing` is true, the onion service ends.
- `/[folder_name]` directory listings of subfolders
- `/[file_name]` if `autostop_sharing` is false, this downloads the actual file (using http gzip compression), and if `autostop_sharing` is true this returns 404

Website mode and share mode share a lot of code. The main difference is website mode has no `/download`, `/[filename]` always downloads the actual file, and `/` only shows a directory listing if there's no `index.html`, and otherwise renders the index page.

## Communicating with the GUI

Each `Web` object has a thread-safe FIFO queue of messages. As the web service is used it pushes messages to the queue, and the GUI reads those messages to update itself.

Here are the types of messages that the current OnionShare desktop supports:

- `REQUEST_LOAD` someone loaded `/`
- `REQUEST_STARTED` someone starting downloading the compressed files at `/download`
- `REQUEST_PROGRESS` progress update on `/download`
- `REQUEST_CANCELED` transfer of `/download` was canceled by the Tor Browser user
- `REQUEST_UPLOAD_INCLUDES_MESSAGE` used for receive mode
- `REQUEST_UPLOAD_FILE_RENAMED` used for receive mode
- `REQUEST_UPLOAD_SET_DIR` used for receive mode
- `REQUEST_UPLOAD_FINISHED` used for receive mode
- `REQUEST_UPLOAD_CANCELED` used for receive mode
- `REQUEST_INDIVIDUAL_FILE_STARTED` used for share and website mode, and individual file started downloading
- `REQUEST_INDIVIDUAL_FILE_PROGRESS` used for share and website mode, update on individual file download
- `REQUEST_INDIVIDUAL_FILE_CANCELED` used for share and website mode, an individual file download was canceled by the Tor Browser user
- `REQUEST_ERROR_DATA_DIR_CANNOT_CREATE` used for receive mode
- `REQUEST_OTHER` an unknown request

The GUI then uses these messages to display a history of downloads, as well as progress bars for current downloads (or uploads, in receive mode), like this:

![Screenshot from 2021-08-27 16-26-55](https://user-images.githubusercontent.com/156128/131197826-1990395b-ee33-45ab-b2bc-54f8e360d12a.png)

## Compression

Because onion services are really slow, it's important to compress all data. The current `Web` object in OnionShare desktop implements code to stream gzip compression of individual files on disk.

And for share mode, if more than one file is shared it compresses everything ahead of time in a zip file, then streams that zip from disk, but doesn't add extra compression on top of it (though I don't think it would hurt).

I think this is a good basic overview of what the shared code between iOS and Android would need to implement for share mode. If we decide to implement receive, website, or chat modes also, I can go into greater detail about those modes too.

**Comment by n8fr8** [comment]
I agree with @micahflee on the scope being the "cli".

We have had great success with shared codebase between Android and iOS using Go with Tor Pluggable Transports. The only downside there is memory usage and binary size. I think the kind of functions outlined here would work very well with a Go codebase.

**Comment by n8fr8** [comment]
That said, given the future of Tor in Rust, and the fact that @tladesignz is feeling good about Rust these days given recent success using it in another project, it makes sense to consider that as well.

I have no idea about how Kotlin multiplatform is on iOS. We are happy using Kotlin in lieu of Java on the Android side for apps of course, but can't get my head around using it as a cross-platform "core lib" type service.

**Comment by tladesignz** [comment]
Ok, so I put some thought into this and it turns out, I actually would prefer another approach:

-> Share the API and a test suite specification, but implement platform-specific.

Why? With all shared code approaches, we also inherit several drawbacks:

- Additional dependencies on other build systems: E.g. with Kotlin cross-platform, the iOS app suddenly [needs to rely on Gradle](https://kotlinlang.org/docs/mobile/integrate-in-existing-app.html#connect-the-framework-to-your-ios-project), which unfortunately becomes more and more horrible in my point of view. (E.g., the recent update to Gradle 7 was **no fun** at all.) I foresee, that this will be really ugly to maintain.
- Additional runtimes: While we had a success with [IPtProxy](https://github.com/tladesignz/IPtProxy) it is actually just a huge workaround to the problem, that you can't have two different Go Mobile libraries at once, since you would then have 2 Go runtimes running, which export symbols, which makes you have a name clash, which makes your project not compile. That means: Should we use a shared Go lib, we could not use IPtProxy to support bridges just out of the box. We would instead need to do the same thing IPtProxy does within OnionShare-Core and therefore have copied code again. Besides that, these runtimes create overheads and memory issues. Esp. thinking about iOS Network Extensions with their 15 MB limits.
- We couldn't depend on nicely prepared libraries like https://github.com/swisspol/GCDWebServer which supports iOS background mode out of the box, but instead would need to use platform independent implementations, which would limit our capability of leveraging the full platform capabilities and work with their restrictions.
- While I really like the approach of Rust, which is quite easy to integrate at least in iOS, it is also the hardest platform to use. I did an implementation of [Clean Insights](http://gitlab.com/cleaninsights/clean-insights-rust-sdk), but I have to admit, it's not nearly where the other implementations in JavaScript, Swift and Kotlin are. It's already hard to write Rust code, but adding a C interface (which would be needed to use it on iOS and Android) is horribly difficult if you're not deep into C (which I am not) and asynchronous Rust is on a whole other level, too. (Which we would definitely need.)


So, in the end, I think it's actually easier to have 2 implementations for Android and iOS (or, if we want, *all* Apple platforms), which will save a lot of work in worrying about compatibility, fixing build issues and struggling with difficult-to-use and poorly supported third platforms. We only loose the write-once-run-twice advantage. From my current point of view, that's actually the cheaper price to pay. 

Sorry.

**Comment by n8fr8** [comment]
@tladesignz may have swayed me here.... 

+1 on "-> Share the API and a test suite specification, but implement platform-specific."... it may be a best way to spend time to have a clear API/specification and to write a solid test/compliance suite, then to wrestle with the frustration and challenges of cross-platform languages and tooling on mobile devices.

The "GCDWebServer" is also a good example where there is a robust module we can use out of the box on the iOS platform, that provides us a huge amount of the functionality we need. We shouldn't discount the complexity of writing a web server.

The only downside to this approach is that, in the end, we would be left with 3 implementations of the same "core" functionality (Python-Desktop, Kotlin-Android, Swift-iOS) to maintain. Perhaps that is unavoidable given that at least some aspects of those apps will be in those languages with native UI and OS integration needs. At some point, the Swift-iOS app could/should become the MacOS desktop app, as well, if we build it right.

**Comment by micahflee** [comment]
I think this makes a lot of sense.

One other thing we lose by having separate implementations though is the anonymity set. With different implementations of the web server, it will be possible to for an attacker with an OnionShare address to fingerprint which platform the service is running on. We can help this some by sharing resources for the frontend (like html templates, css, js) but I don't think we'll be able to smooth out the differences in web server implementation itself.

Still though, separate implementations is probably the way to go.

**Comment by tladesignz** [comment]
> With different implementations of the web server, it will be possible to for an attacker with an OnionShare address to fingerprint which platform the service is running on.

Ah, interesting aspect. You think, the underlying network stacks of the platforms aren't already distinguishable anyway when using the same server code on top?

**Comment by grote** [comment]
If an attacker can connect to our onion service, knowing which OS it is running on is maybe a smaller problem than being able to download the files it provides.

**Comment by n8fr8** [comment]
I think we've resolved this issue.
